Upgrade to matrix-appservice-bridge 5.0.0
matrix-org/matrix-appservice-slack pull request #690
Opened 2022-07-26 10:12 UTC by Half-Shot

This includes a minimum Node version bump to Node.JS 16.0.

2022-07-26 18:41 UTC, AndrewFerr reviewed
I just skimmed through the typing cleanups, but they look fine overall.  Lint warnings are also down a bit (-13), which is nice.

2022-07-26 18:41 UTC, AndrewFerr commented on src/AdminCommands.ts
> +                // to avoid further pain this just assunes that the handler/yargs
Nitpick, "assunes" -> "assumes"

2022-07-26 18:41 UTC, AndrewFerr commented on tests/integration/HttpTests.ts
> +        const res = await axios.get("http://127.0.0.1:57000/health");
Out of curiosity, what broke without this?

2022-07-26 18:41 UTC, AndrewFerr commented on package.json
> +    "node": ">=16 18<="
`>=16 <=18`

2022-07-28 14:00 UTC, tadzik requested changes
Needs fixes to the Dockerfile, as it currently fails to start due to:

```
Error: Cannot find module '@matrix-org/matrix-sdk-crypto-nodejs-linux-x64-gnu'
```

Dropping `--ignore-scripts` fixes it

2022-07-29 15:31 UTC, tadzik approved these changes

2022-07-29 15:56 UTC, merged