Add a way to measure test coverage
matrix-org/matrix-appservice-slack pull request #777
Opened 2024-03-28 13:39 UTC by tadzik

We had some leftovers of it in .gitignore, now it's actually available as a command

2024-04-04 14:35 UTC, Cadair approved these changes
I wont pretend to be able to fully understand this incantation, but if it works then horray.

2024-04-16 11:29 UTC, Half-Shot requested changes
Changelog please :)

2024-04-16 11:29 UTC, Half-Shot commented on package.json
> +    "node-mocks-http": "^1.14.1",
hello?

2024-04-17 09:12 UTC, tadzik commented on package.json
> +    "node-mocks-http": "^1.14.1",
[Is it me you're looking for?](https://youtu.be/Cwnrsd5so9M?t=27)

(Removed in dc9bc72b146c931b6447f386b8aa844e5ebec073, thanks!)

2024-06-05 14:09 UTC, merged