User correct Matrix accounts when redacting events
matrix-org/matrix-appservice-slack pull request #780
Opened 2024-03-29 10:44 UTC by tadzik

Fixes https://github.com/matrix-org/matrix-appservice-slack/issues/766

For events sent from Slack and later deleted from Slack, we use the same Slack Ghost that sent the message – this alleviates the need for an elevated Power Level.

For events sent from Matrix and deleted from Slack, we try to use our bot account. This does require us to have a sufficient power level, so we try to be helpful in the logs if we don't.

Note: Slack doesn't tell us who deleted the message, so we can't bridge that precisely – the sender of a redact event is just our best effort.

2024-03-29 10:45 UTC, tadzik commented on src/BaseSlackHandler.ts
> +    team?: string;
I have not actually seen `team_id` in incoming Slack messages, and the only place I see it used is when it's artificially assigned to in SlackRTMHandler – perhaps it's an error in our typing?

2024-03-29 10:45 UTC, tadzik commented on src/SlackEventHandler.ts
> +                    // Sent from Matrix, try to remove it with our bot account
Hrm, should actually check if it's indeed *our* bot account...

2024-04-05 09:07 UTC, Half-Shot requested changes
Some thoughts.

2024-04-05 09:07 UTC, Half-Shot commented on src/SlackEventHandler.ts
> +                    await ghost.redactEvent(originalEvent.roomId, originalEvent.eventId);
Should we try with the botClient if this fails, as a fallback?

2024-04-05 09:07 UTC, Half-Shot commented on src/SlackEventHandler.ts
> +                    log.error("Cannot redact Slack message if we don't know the original sender:", previousMessage);
can we just use the botClient?

2024-04-05 09:07 UTC, Half-Shot commented on src/BaseSlackHandler.ts
> +    team?: string;
I don't really remember when this was introduced, it's possible it's invalid and team_id is the right one.

2024-04-05 09:47 UTC, tadzik commented on src/SlackEventHandler.ts
> +                    await ghost.redactEvent(originalEvent.roomId, originalEvent.eventId);
Done in b4f2911c5a102b72825db225b3129887523bcdf0

2024-04-05 09:48 UTC, tadzik commented on src/SlackEventHandler.ts
> +                    log.error("Cannot redact Slack message if we don't know the original sender:", previousMessage);
Done in b4f2911c5a102b72825db225b3129887523bcdf0; this has a side effect of us trying to delete messages sent by originally-Matrix users with the slack bot – which probably makes sense.

2024-04-16 11:32 UTC, Half-Shot requested changes
Good to go after changelog.

2024-04-17 09:16 UTC, tadzik commented
> Good to go after changelog.

Added in e2df892

2024-04-29 09:33 UTC, merged